In [1]:
import numpy as np

# 1创建

In [2]:
score=np.array([[1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]])

In [3]:
score


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

# 2、效率对比

In [6]:
import random
import time
import numpy as np

a=[]
for i in range(100000000):
    a.append(random.random())

#通过%time魔法方法，查看当前代码运行一次的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

CPU times: total: 2.59 s
Wall time: 3.02 s
CPU times: total: 203 ms
Wall time: 241 ms


# 3、ndarray的属性

In [7]:
#ndarray.shape        数组维度的元素
#ndarray.ndim         数组维数
#ndarray.size         数组中的元素数量
#ndarray.itemsize     一个数组元素的长度（字节）
#ndarray.dtype        数组元素的类型
score.shape

(5, 5)

In [8]:
score.ndim

2

In [9]:
score.size

25

In [10]:
score.itemsize


4

In [11]:
score.dtype

dtype('int32')

# 4、ndarray的形状

In [14]:
a = np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

In [16]:
b = np.array([[1,2,3],[1,2,4]])

In [17]:
b


array([[1, 2, 3],
       [1, 2, 4]])

In [20]:
c= np.array([[[1,2,3],[1,2,3]],[[1,2,3],[2,3,4]]])

In [21]:
c


array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [23]:
print(a.shape)
print(b.shape)
print(c.shape)  #两大块，每一块两行三列

(3,)
(2, 3)
(2, 2, 3)


In [24]:
c.ndim

3

# 5、ndarray的类型

In [25]:
a.dtype

dtype('int32')

In [26]:
d= np.array([1,2,3],dtype=np.float32)

In [27]:
d


array([1., 2., 3.], dtype=float32)

In [28]:
d.dtype

dtype('float32')

In [29]:
e= np.array(["ai","python","love"],dtype= np.string_)


In [30]:
e


array([b'ai', b'python', b'love'], dtype='|S6')