In [1]:
import numpy as np

In [2]:
stock_change=np.random.uniform(0,1,(8,10))

In [3]:
stock_change

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957,
        0.67047782, 0.44032463, 0.54288587, 0.54501066, 0.25995702],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308,
        0.42696661, 0.6827615 , 0.91365329, 0.18803421, 0.33700603],
       [0.52813936, 0.48294942, 0.478084  , 0.76579502, 0.16547416,
        0.2797605 , 0.99255868, 0.41317161, 0.98039524, 0.14347866],
       [0.42944929, 0.03329215, 0.48341117, 0.91161426, 0.1202865 ,
        0.85152614, 0.82762998, 0.80397357, 0.26114866, 0.95022965],
       [0.83471635, 0.91111898, 0.12605874, 0.6644873 , 0.58771259,
        0.76375216, 0.29072959, 0.14848492, 0.33282237, 0.42795253],
       [0.15788368, 0.80504216, 0.00261759, 0.31578633, 0.46158407,
        0.43374252, 0.14093888, 0.1933002 , 0.57566149, 0.5700672 ],
       [0.32575637, 0.63216714, 0.45466494, 0.21513936, 0.08170111,
        0.41588334, 0.62609834, 0.9923569 , 0.98135785, 0.83740294],
       [0.91958764, 0.94109483, 0.3622341

In [4]:
stoch_c=stock_change[0:5,0:5]

In [5]:
stoch_c

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308],
       [0.52813936, 0.48294942, 0.478084  , 0.76579502, 0.16547416],
       [0.42944929, 0.03329215, 0.48341117, 0.91161426, 0.1202865 ],
       [0.83471635, 0.91111898, 0.12605874, 0.6644873 , 0.58771259]])

In [6]:
stoch_c>1

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
stock_d=stock_change[0:2,0:5]

In [8]:
stock_d

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308]])

In [10]:
np.where(stock_d>0.5,1,0)    #三目运算符

array([[0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1]])

In [11]:
stock_d

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308]])

In [12]:
np.where(np.logical_and(stock_d>0.5,stock_d<0.8),1,0)

array([[0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [13]:
stock_d

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308]])

In [14]:
stock_change.max()

0.9925586845402956

In [15]:
stock_change

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957,
        0.67047782, 0.44032463, 0.54288587, 0.54501066, 0.25995702],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308,
        0.42696661, 0.6827615 , 0.91365329, 0.18803421, 0.33700603],
       [0.52813936, 0.48294942, 0.478084  , 0.76579502, 0.16547416,
        0.2797605 , 0.99255868, 0.41317161, 0.98039524, 0.14347866],
       [0.42944929, 0.03329215, 0.48341117, 0.91161426, 0.1202865 ,
        0.85152614, 0.82762998, 0.80397357, 0.26114866, 0.95022965],
       [0.83471635, 0.91111898, 0.12605874, 0.6644873 , 0.58771259,
        0.76375216, 0.29072959, 0.14848492, 0.33282237, 0.42795253],
       [0.15788368, 0.80504216, 0.00261759, 0.31578633, 0.46158407,
        0.43374252, 0.14093888, 0.1933002 , 0.57566149, 0.5700672 ],
       [0.32575637, 0.63216714, 0.45466494, 0.21513936, 0.08170111,
        0.41588334, 0.62609834, 0.9923569 , 0.98135785, 0.83740294],
       [0.91958764, 0.94109483, 0.3622341

In [16]:
stock_d.argmax()

7

In [17]:
stock_d

array([[0.32156861, 0.20677233, 0.55080004, 0.56201335, 0.49771957],
       [0.7297074 , 0.91545762, 0.94732596, 0.366916  , 0.73018308]])

In [18]:
stock_d.argmax(axis=1)  # 手动试一下axis=1、axis=0是按行还是按列

array([3, 2], dtype=int64)

In [20]:
stock_d.max(axis=0)

array([0.7297074 , 0.91545762, 0.94732596, 0.56201335, 0.73018308])

In [21]:
stock_d.argmax(axis=1)   # 第一行第二行的最大值下标

array([3, 2], dtype=int64)

In [22]:
stock_d.argmax(axis=0)

array([1, 1, 1, 0, 1], dtype=int64)

# 数组运算

In [23]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [24]:
arr+1

array([2, 3, 4, 5])

In [25]:
arr/2

array([0.5, 1. , 1.5, 2. ])

In [26]:
arr*5

array([ 5, 10, 15, 20])

In [31]:
ar1=np.array([[1],[3]])
ar2=np.array([[1,2,3,2,1,4],[5,6,1,2,3,2]])

In [32]:
ar1+ar2      #数组和数组计算需要满足广播机制：维度相同，shape对应位置为1

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 5]])

In [33]:
a=np.array([[80,86],
            [82,80],
            [85,78],
            [98,80],
            [78,90],
            [90,88]])


In [34]:
b=np.array([[0.7],[0.3]])

In [35]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [92.6],
       [81.6],
       [89.4]])

In [36]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [92.6],
       [81.6],
       [89.4]])

In [37]:
np.dot(a,10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [980, 800],
       [780, 900],
       [900, 880]])

In [39]:
# np.matmul(a,10)   #matmul不支持矩阵乘以个数字 