In [1]:
import numpy as np

# 1、生成数组

In [2]:
ones=np.ones([4,8])

In [3]:
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
ones.dtype

dtype('float64')

In [5]:
np.zeros_like(ones)  #np.zeros_like(ones)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
a= np.array([[1,2,3],[4,5,6]])

In [7]:
a1= np.array(a)   #深拷贝

In [8]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a2= np.asarray(a)   #浅拷贝

In [10]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a[0,0]=1000

In [12]:
a

array([[1000,    2,    3],
       [   4,    5,    6]])

In [13]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a2

array([[1000,    2,    3],
       [   4,    5,    6]])

In [16]:
np.linspace(0,100,11)  #11代表等间隔11个数字

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
np.arange(10,50,2)     #2代表步长为2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [23]:
np.logspace(0,1,2)  #2代表输出两个值，10的0次方，10的1次方

array([ 1., 10.])